// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgBiEqPuqEZAod-NgwWhYNLb_F94FTMTc',
    appId: '1:524259812223:web:988572878c88acbe52304a',
    messagingSenderId: '524259812223',
    projectId: 'teamup-ea2b9',
    authDomain: 'teamup-ea2b9.firebaseapp.com',
    storageBucket: 'teamup-ea2b9.firebasestorage.app',
    measurementId: 'G-068JV1EQTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-Yuy7Z9vqUeCn8BYR6OXIQ7xwpWoCJw',
    appId: '1:524259812223:android:dacde64f06fc3aae52304a',
    messagingSenderId: '524259812223',
    projectId: 'teamup-ea2b9',
    storageBucket: 'teamup-ea2b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvf2DPPb_qZo3zrcB3KI4vmNc71yu-SXU',
    appId: '1:524259812223:ios:e8a5c26f19cc1ef452304a',
    messagingSenderId: '524259812223',
    projectId: 'teamup-ea2b9',
    storageBucket: 'teamup-ea2b9.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );
}
